# Generated by Django 4.2 on 2023-04-28 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_article"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="category",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
