# Generated by Django 4.2 on 2023-05-02 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_article_category"),
    ]

    operations = [
        migrations.RenameField(
            model_name="restaurant",
            old_name="location_lat",
            new_name="lat",
        ),
        migrations.RenameField(
            model_name="restaurant",
            old_name="location_long",
            new_name="long",
        ),
        migrations.AddField(
            model_name="restaurant",
            name="location",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="number",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
