# Generated by Django 4.2 on 2023-05-03 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_rename_location_lat_restaurant_lat_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="pwd",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
